name: Build and Deploy Doxygen Docs to GitHub Pages

on:
  push:
    branches: [ main ]
    
jobs:
  generate-and-deploy-documentation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
        
    - name: Generate doxygen documentation
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        doxyfile-path: "./Doxyfile" # Path to Doxyfile
        working-directory: "." # Working directory
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
